// Central data store for VastraWise — Men's Wear & Groom Rental System

export interface Outfit {
    id: string
    name: string
    category: string
    rentPrice: number
    securityDeposit?: number
    status: 'available' | 'rented' | 'maintenance'
    imageUrl: string
    description?: string
    size?: string
    chestSize?: string
    waistSize?: string
    fitType?: 'Slim Fit' | 'Regular Fit' | 'Royal Tailored'
    color?: string
    includedAccessories?: string[]
    marketRetailPrice?: number
    marketDemand?: 'High' | 'Very High' | 'Trending' | 'Classic Peak' | 'Moderate'
    marketTrendNote?: string
}

export interface Customer {
    id: string
    name: string
    initials: string
    avatarColor: string
    email: string
    phone: string
    location: string
    status: 'active' | 'inactive'
    totalRentals: number
    totalSpent: number
    joinDate: string
}

export interface Invoice {
    id: string
    customerId: string
    customerName: string
    outfitId: string
    outfitName: string
    amount: number
    securityDeposit?: number
    depositStatus?: 'held' | 'refunded' | 'forfeited'
    date: string
    returnDate: string
    trialDate?: string
    eventDate?: string
    includedAccessories?: string[]
    alterationNotes?: string
    status: 'paid' | 'pending' | 'overdue'
}

// ── SEED DATA (Men's Luxury Wear & Groom Collection) ──────────────────────────

export const CATEGORIES = [
  'Sherwanis',
  'Jodhpuri / Bandhgala',
  'Indo-Western',
  'Kurtas',
  'Kurta Sets',
  'Jackets',
  'Pathani Wear',
  'Bottom Wear',
  'Dhoti Collection',
  'Formal / Occasion Wear',
  'Wedding Collection',
  'Regional Traditional Wear',
  'Premium Collection',
  'Accessories',
  'Other'
]

export const INITIAL_OUTFITS: Outfit[] = [
    {
        "id": "OUT-001",
        "name": "Classic Sherwani",
        "category": "Sherwanis",
        "rentPrice": 2999,
        "securityDeposit": 2000,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&q=80",
        "description": "Classic silk cream sherwani with subtle self-embroidery, high collar mandarin neck, and polished brass royal buttons.",
        "size": "40 (M)",
        "chestSize": "40\"",
        "waistSize": "34\"",
        "fitType": "Royal Tailored",
        "color": "Cream & Gold Silk",
        "includedAccessories": [
            "Royal Turban (Safa)",
            "Designer Brooch",
            "Pearl Necklace"
        ],
        "marketRetailPrice": 22000,
        "marketDemand": "High",
        "marketTrendNote": "Classic cream silk sherwani with subtle self-embroidery and mandarin collar."
    },
    {
        "id": "OUT-002",
        "name": "Wedding Sherwani",
        "category": "Sherwanis",
        "rentPrice": 4999,
        "securityDeposit": 3000,
        "status": "rented",
        "imageUrl": "https://images.unsplash.com/photo-1610189019599-3e0fa1c2a8a2?w=800&q=80",
        "description": "Grand groom wedding sherwani adorned with heavy hand-knotted zardozi embroidery and antique gold threadwork.",
        "size": "42 (L)",
        "chestSize": "42\"",
        "waistSize": "36\"",
        "fitType": "Royal Tailored",
        "color": "Deep Maroon & Antique Gold",
        "includedAccessories": [
            "Embroidered Dupatta",
            "Royal Turban (Safa)",
            "Pearl Necklace",
            "Kalgi Pin"
        ],
        "marketRetailPrice": 45000,
        "marketDemand": "Very High",
        "marketTrendNote": "Heavy maroon & antique gold groom sherwani with zardozi embroidery."
    },
    {
        "id": "OUT-003",
        "name": "Indo-Pak Sherwani",
        "category": "Sherwanis",
        "rentPrice": 3800,
        "securityDeposit": 2500,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&q=80",
        "description": "South Asian fusion long-flared sherwani featuring layered front panels and metallic thread motifs.",
        "size": "38 (S)",
        "chestSize": "38\"",
        "waistSize": "32\"",
        "fitType": "Slim Fit",
        "color": "Midnight Blue & Silver",
        "includedAccessories": [
            "Silk Dupatta",
            "Metallic Brooch",
            "Churidar"
        ],
        "marketRetailPrice": 35000,
        "marketDemand": "Trending",
        "marketTrendNote": "Modern flared asymmetric sherwani featuring layered front panels."
    },
    {
        "id": "OUT-004",
        "name": "Achkan Sherwani",
        "category": "Sherwanis",
        "rentPrice": 2799,
        "securityDeposit": 1800,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1617922001439-4a2e6562f328?w=800&q=80",
        "description": "Sleek Achkan sherwani tailored from woven silk brocade with signature front button closure.",
        "size": "40 (M)",
        "chestSize": "40\"",
        "waistSize": "34\"",
        "fitType": "Regular Fit",
        "color": "Ivory Brocade",
        "includedAccessories": [
            "Pocket Square",
            "Aligarhi Pajama",
            "Emerald Brooch"
        ],
        "marketRetailPrice": 24000,
        "marketDemand": "High",
        "marketTrendNote": "Knee-length structured Achkan sherwani in woven silk brocade."
    },
    {
        "id": "OUT-005",
        "name": "Designer Sherwani",
        "category": "Sherwanis",
        "rentPrice": 5499,
        "securityDeposit": 3500,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1610189019599-3e0fa1c2a8a2?w=800&q=80",
        "description": "Exclusive runway designer groom sherwani with 3D raised floral motifs and hand-cut sequin borders.",
        "size": "42 (L)",
        "chestSize": "42\"",
        "waistSize": "36\"",
        "fitType": "Royal Tailored",
        "color": "Champagne Gold & Pastel Rose",
        "includedAccessories": [
            "Designer Dupatta",
            "Gold Safa",
            "Pearl Necklace",
            "Pocket Pin"
        ],
        "marketRetailPrice": 55000,
        "marketDemand": "Very High",
        "marketTrendNote": "Runway designer groom sherwani in champagne gold with 3D floral motifs."
    },
    {
        "id": "OUT-006",
        "name": "Velvet Sherwani",
        "category": "Sherwanis",
        "rentPrice": 4299,
        "securityDeposit": 2800,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&q=80",
        "description": "Plush royal navy velvet sherwani accented with gold bullion embroidery on mandarin collar and sleeves.",
        "size": "40 (M)",
        "chestSize": "40\"",
        "waistSize": "34\"",
        "fitType": "Royal Tailored",
        "color": "Royal Navy Velvet",
        "includedAccessories": [
            "Embroidered Velvet Dupatta",
            "Brass Brooch",
            "Velvet Mojari"
        ],
        "marketRetailPrice": 38000,
        "marketDemand": "Trending",
        "marketTrendNote": "Plush royal navy velvet sherwani accented with gold bullion embroidery."
    },
    {
        "id": "OUT-007",
        "name": "Embroidered Sherwani",
        "category": "Sherwanis",
        "rentPrice": 3499,
        "securityDeposit": 2200,
        "status": "rented",
        "imageUrl": "https://images.unsplash.com/photo-1610189019599-3e0fa1c2a8a2?w=800&q=80",
        "description": "Pastel blush raw silk sherwani intricately embroidered with resham and zari floral vines.",
        "size": "38 (S)",
        "chestSize": "38\"",
        "waistSize": "32\"",
        "fitType": "Regular Fit",
        "color": "Pastel Blush Pink",
        "includedAccessories": [
            "Pink Turban",
            "Silk Dupatta",
            "Pearl Strand"
        ],
        "marketRetailPrice": 30000,
        "marketDemand": "High",
        "marketTrendNote": "Blush pink raw silk sherwani intricately embroidered with resham thread."
    },
    {
        "id": "OUT-008",
        "name": "Printed Sherwani",
        "category": "Sherwanis",
        "rentPrice": 2299,
        "securityDeposit": 1500,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=800&q=80",
        "description": "Contemporary floral printed silk sherwani with soft pastel hues for outdoor wedding functions.",
        "size": "40 (M)",
        "chestSize": "40\"",
        "waistSize": "34\"",
        "fitType": "Slim Fit",
        "color": "Floral Mint Green",
        "includedAccessories": [
            "Silk Pocket Square",
            "Pearl Necklace"
        ],
        "marketRetailPrice": 18000,
        "marketDemand": "High",
        "marketTrendNote": "Contemporary floral printed silk sherwani for daytime Sangeet and Mehendi."
    },
    {
        "id": "OUT-009",
        "name": "Jodhpuri Sherwani",
        "category": "Sherwanis",
        "rentPrice": 3699,
        "securityDeposit": 2400,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1617922001439-4a2e6562f328?w=800&q=80",
        "description": "Royal Jodhpuri sherwani crafted with stand-up bandhgala collar, velvet lapels, and custom brass crest buttons.",
        "size": "42 (L)",
        "chestSize": "42\"",
        "waistSize": "36\"",
        "fitType": "Regular Fit",
        "color": "Imperial Charcoal & Gold",
        "includedAccessories": [
            "Hand-carved Brass Buttons",
            "Royal Safa",
            "Pocket Square"
        ],
        "marketRetailPrice": 32000,
        "marketDemand": "Classic Peak",
        "marketTrendNote": "Royal Jodhpuri sherwani crafted with stand-up bandhgala collar and velvet lapels."
    },
    {
        "id": "OUT-010",
        "name": "Jodhpuri Suit",
        "category": "Jodhpuri / Bandhgala",
        "rentPrice": 2499,
        "securityDeposit": 1800,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1617922001439-4a2e6562f328?w=800&q=80",
        "description": "Classic royal Jodhpuri suit cut from fine Italian wool blend with hand-cast brass crest buttons.",
        "size": "40 (M)",
        "chestSize": "40\"",
        "waistSize": "34\"",
        "fitType": "Regular Fit",
        "color": "Navy Blue & Antique Brass",
        "includedAccessories": [
            "Silk Pocket Square",
            "Brass Cufflinks"
        ],
        "marketRetailPrice": 22000,
        "marketDemand": "High",
        "marketTrendNote": "Classic navy blue Jodhpuri suit with tailored trousers and brass buttons."
    },
    {
        "id": "OUT-011",
        "name": "Bandhgala Suit",
        "category": "Jodhpuri / Bandhgala",
        "rentPrice": 2799,
        "securityDeposit": 2000,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&q=80",
        "description": "High-neck black Bandhgala suit with satin collar trim and formal tailored slim trousers.",
        "size": "38 (S)",
        "chestSize": "38\"",
        "waistSize": "32\"",
        "fitType": "Slim Fit",
        "color": "Jet Black Silk Blend",
        "includedAccessories": [
            "Satin Pocket Square",
            "Silver Cufflinks"
        ],
        "marketRetailPrice": 25000,
        "marketDemand": "Very High",
        "marketTrendNote": "High-neck black Bandhgala suit with satin collar trim and formal trousers."
    },
    {
        "id": "OUT-012",
        "name": "Prince Coat",
        "category": "Jodhpuri / Bandhgala",
        "rentPrice": 2299,
        "securityDeposit": 1500,
        "status": "rented",
        "imageUrl": "https://images.unsplash.com/photo-1617922001439-4a2e6562f328?w=800&q=80",
        "description": "Tailored Prince Coat jacket featuring royal crest buttons, padded shoulders, and structured chest line.",
        "size": "40 (M)",
        "chestSize": "40\"",
        "waistSize": "34\"",
        "fitType": "Slim Fit",
        "color": "Royal Wine Red",
        "includedAccessories": [
            "Metallic Lapel Pin",
            "Pocket Square"
        ],
        "marketRetailPrice": 20000,
        "marketDemand": "Trending",
        "marketTrendNote": "Tailored Prince Coat jacket featuring royal crest buttons and padded shoulders."
    },
    {
        "id": "OUT-013",
        "name": "Royal Jodhpuri",
        "category": "Jodhpuri / Bandhgala",
        "rentPrice": 3299,
        "securityDeposit": 2200,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1610189019599-3e0fa1c2a8a2?w=800&q=80",
        "description": "Rich emerald green suede Jodhpuri suit embellished with handcrafted silver zardozi neck work.",
        "size": "42 (L)",
        "chestSize": "42\"",
        "waistSize": "36\"",
        "fitType": "Royal Tailored",
        "color": "Emerald Green Suede",
        "includedAccessories": [
            "Silver Zardozi Brooch",
            "Silk Pocket Square"
        ],
        "marketRetailPrice": 30000,
        "marketDemand": "High",
        "marketTrendNote": "Emerald green suede Jodhpuri suit with silver zardozi neck embroidery."
    },
    {
        "id": "OUT-014",
        "name": "Embroidered Jodhpuri",
        "category": "Jodhpuri / Bandhgala",
        "rentPrice": 2999,
        "securityDeposit": 2000,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1617922001439-4a2e6562f328?w=800&q=80",
        "description": "Plum Jodhpuri jacket featuring delicate floral thread embroidery along shoulder seams and collar.",
        "size": "40 (M)",
        "chestSize": "40\"",
        "waistSize": "34\"",
        "fitType": "Regular Fit",
        "color": "Deep Plum & Rose Gold",
        "includedAccessories": [
            "Rose Gold Cufflinks",
            "Pocket Square"
        ],
        "marketRetailPrice": 28000,
        "marketDemand": "High",
        "marketTrendNote": "Plum Jodhpuri jacket featuring delicate floral thread embroidery."
    },
    {
        "id": "OUT-015",
        "name": "Velvet Bandhgala",
        "category": "Jodhpuri / Bandhgala",
        "rentPrice": 3199,
        "securityDeposit": 2200,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&q=80",
        "description": "Luxury micro-velvet Bandhgala jacket with satin trim lapels and matching wool trousers.",
        "size": "42 (L)",
        "chestSize": "42\"",
        "waistSize": "36\"",
        "fitType": "Slim Fit",
        "color": "Midnight Velvet & Black",
        "includedAccessories": [
            "Velvet Bow Tie",
            "Custom Cufflinks"
        ],
        "marketRetailPrice": 29000,
        "marketDemand": "Trending",
        "marketTrendNote": "Luxury micro-velvet Bandhgala jacket with satin lapel trim."
    },
    {
        "id": "OUT-016",
        "name": "Indo-Western Suit",
        "category": "Indo-Western",
        "rentPrice": 2499,
        "securityDeposit": 1800,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&q=80",
        "description": "Contemporary tuxedo-cut Indo-Western suit featuring mandarin collar and slim trousers.",
        "size": "40 (M)",
        "chestSize": "40\"",
        "waistSize": "34\"",
        "fitType": "Slim Fit",
        "color": "Steel Blue & Chrome",
        "includedAccessories": [
            "Metallic Brooch",
            "Pocket Square"
        ],
        "marketRetailPrice": 22000,
        "marketDemand": "High",
        "marketTrendNote": "Contemporary tuxedo-cut Indo-Western suit with mandarin collar."
    },
    {
        "id": "OUT-017",
        "name": "Indo-Western Sherwani",
        "category": "Indo-Western",
        "rentPrice": 3499,
        "securityDeposit": 2200,
        "status": "maintenance",
        "imageUrl": "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&q=80",
        "description": "Fusion sherwani jacket with diagonal western tuxedo cut hemline and intricate Indian raw silk weave.",
        "size": "42 (L)",
        "chestSize": "42\"",
        "waistSize": "36\"",
        "fitType": "Royal Tailored",
        "color": "Ivory & Matte Black",
        "includedAccessories": [
            "Designer Brooch",
            "Silk Dupatta"
        ],
        "marketRetailPrice": 32000,
        "marketDemand": "Very High",
        "marketTrendNote": "Fusion sherwani jacket with diagonal western tuxedo cut hemline."
    },
    {
        "id": "OUT-018",
        "name": "Draped Indo-Western",
        "category": "Indo-Western",
        "rentPrice": 2999,
        "securityDeposit": 2000,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&q=80",
        "description": "Avant-garde draped Indo-Western top with pleated inner cowl layer and open structured outer jacket.",
        "size": "38 (S)",
        "chestSize": "38\"",
        "waistSize": "32\"",
        "fitType": "Slim Fit",
        "color": "Charcoal & Silver Cowl",
        "includedAccessories": [
            "Silver Chain Brooch",
            "Slim Trousers"
        ],
        "marketRetailPrice": 26000,
        "marketDemand": "Trending",
        "marketTrendNote": "Avant-garde draped Indo-Western top with pleated inner cowl layer."
    },
    {
        "id": "OUT-019",
        "name": "Asymmetric Indo-Western",
        "category": "Indo-Western",
        "rentPrice": 2799,
        "securityDeposit": 1800,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&q=80",
        "description": "Asymmetric diagonal buttoned jacket paired with soft cowl silk kurta and slim trousers.",
        "size": "40 (M)",
        "chestSize": "40\"",
        "waistSize": "34\"",
        "fitType": "Slim Fit",
        "color": "Wine Maroon & Gold",
        "includedAccessories": [
            "Gold Brooch",
            "Cowl Kurta"
        ],
        "marketRetailPrice": 25000,
        "marketDemand": "Trending",
        "marketTrendNote": "Asymmetric diagonal buttoned jacket paired with soft cowl silk kurta."
    },
    {
        "id": "OUT-020",
        "name": "Jacket Style Indo-Western",
        "category": "Indo-Western",
        "rentPrice": 2699,
        "securityDeposit": 1800,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1610189019599-3e0fa1c2a8a2?w=800&q=80",
        "description": "3-piece fusion suit with open jacquard long jacket, fitted inner silk tunic, and tailored pants.",
        "size": "40 (M)",
        "chestSize": "40\"",
        "waistSize": "34\"",
        "fitType": "Regular Fit",
        "color": "Teal & Jacquard Gold",
        "includedAccessories": [
            "Pocket Square",
            "Metallic Lapel Pin"
        ],
        "marketRetailPrice": 24000,
        "marketDemand": "High",
        "marketTrendNote": "3-piece fusion suit with open jacquard long jacket and inner tunic."
    },
    {
        "id": "OUT-021",
        "name": "Fusion Indo-Western",
        "category": "Indo-Western",
        "rentPrice": 2899,
        "securityDeposit": 1900,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&q=80",
        "description": "Crossover lapel collar fusion jacket featuring geometric sequin embroidery and contrast churidar.",
        "size": "42 (L)",
        "chestSize": "42\"",
        "waistSize": "36\"",
        "fitType": "Slim Fit",
        "color": "Black & Champagne Gold",
        "includedAccessories": [
            "Champagne Brooch",
            "Churidar"
        ],
        "marketRetailPrice": 26000,
        "marketDemand": "High",
        "marketTrendNote": "Crossover lapel collar fusion jacket with sequin embroidery."
    },
    {
        "id": "OUT-022",
        "name": "Simple Kurta",
        "category": "Kurtas",
        "rentPrice": 399,
        "securityDeposit": 300,
        "status": "rented",
        "imageUrl": "https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?w=800&q=80",
        "description": "Clean minimalist solid white cotton-silk straight knee-length kurta with mandarin collar.",
        "size": "40 (M)",
        "chestSize": "40\"",
        "waistSize": "34\"",
        "fitType": "Regular Fit",
        "color": "Pure White Cotton-Silk",
        "includedAccessories": [
            "Cotton Pajama"
        ],
        "marketRetailPrice": 3500,
        "marketDemand": "Moderate",
        "marketTrendNote": "Clean minimalist solid white cotton-silk straight kurta."
    },
    {
        "id": "OUT-023",
        "name": "Cotton Kurta",
        "category": "Kurtas",
        "rentPrice": 349,
        "securityDeposit": 250,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&q=80",
        "description": "Breathable handloom organic cotton kurta with comfortable side slits and mandarin collar.",
        "size": "38 (S)",
        "chestSize": "38\"",
        "waistSize": "32\"",
        "fitType": "Regular Fit",
        "color": "Sky Blue Organic Cotton",
        "includedAccessories": [
            "White Pajama"
        ],
        "marketRetailPrice": 2500,
        "marketDemand": "High",
        "marketTrendNote": "Breathable handloom organic cotton kurta for Haldi and morning rituals."
    },
    {
        "id": "OUT-024",
        "name": "Linen Kurta",
        "category": "Kurtas",
        "rentPrice": 599,
        "securityDeposit": 400,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=800&q=80",
        "description": "Premium pure linen pastel beige kurta offering casual luxury and breathable comfort.",
        "size": "40 (M)",
        "chestSize": "40\"",
        "waistSize": "34\"",
        "fitType": "Slim Fit",
        "color": "Pastel Beige Linen",
        "includedAccessories": [
            "Linen Pajama"
        ],
        "marketRetailPrice": 4500,
        "marketDemand": "Trending",
        "marketTrendNote": "Premium pure linen pastel beige kurta offering casual luxury."
    },
    {
        "id": "OUT-025",
        "name": "Silk Kurta",
        "category": "Kurtas",
        "rentPrice": 899,
        "securityDeposit": 600,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1610189019599-3e0fa1c2a8a2?w=800&q=80",
        "description": "Luminous Dupion raw silk kurta in vibrant mustard yellow with subtle self-shine.",
        "size": "42 (L)",
        "chestSize": "42\"",
        "waistSize": "36\"",
        "fitType": "Regular Fit",
        "color": "Mustard Yellow Raw Silk",
        "includedAccessories": [
            "Silk Churidar"
        ],
        "marketRetailPrice": 7500,
        "marketDemand": "High",
        "marketTrendNote": "Luminous Dupion raw silk kurta in vibrant mustard yellow for Haldi."
    },
    {
        "id": "OUT-026",
        "name": "Embroidered Kurta",
        "category": "Kurtas",
        "rentPrice": 1199,
        "securityDeposit": 800,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?w=800&q=80",
        "description": "Handcrafted Lucknowi Chikankari embroidered threadwork kurta with shadow work detail.",
        "size": "40 (M)",
        "chestSize": "40\"",
        "waistSize": "34\"",
        "fitType": "Regular Fit",
        "color": "Off-White Chikankari",
        "includedAccessories": [
            "Churidar",
            "Pearl Pin"
        ],
        "marketRetailPrice": 9500,
        "marketDemand": "Very High",
        "marketTrendNote": "Handcrafted Lucknowi Chikankari embroidered threadwork kurta."
    },
    {
        "id": "OUT-027",
        "name": "Printed Kurta",
        "category": "Kurtas",
        "rentPrice": 699,
        "securityDeposit": 500,
        "status": "rented",
        "imageUrl": "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=800&q=80",
        "description": "Artisan Jaipur block-printed floral kurta in soft sage green for lively festive occasions.",
        "size": "38 (S)",
        "chestSize": "38\"",
        "waistSize": "32\"",
        "fitType": "Slim Fit",
        "color": "Sage Green Floral Print",
        "includedAccessories": [
            "Cotton Pajama"
        ],
        "marketRetailPrice": 5500,
        "marketDemand": "Trending",
        "marketTrendNote": "Artisan Jaipur block-printed floral kurta in soft sage green."
    },
    {
        "id": "OUT-028",
        "name": "Pathani Kurta",
        "category": "Kurtas",
        "rentPrice": 799,
        "securityDeposit": 500,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?w=800&q=80",
        "description": "Heavy cotton Pathani kurta featuring front flap pockets, shoulder epaulettes, and roll-up sleeves.",
        "size": "42 (L)",
        "chestSize": "42\"",
        "waistSize": "36\"",
        "fitType": "Regular Fit",
        "color": "Olive Green Heavy Cotton",
        "includedAccessories": [
            "Salwar Pants"
        ],
        "marketRetailPrice": 6000,
        "marketDemand": "High",
        "marketTrendNote": "Heavy cotton Pathani kurta featuring front flap pockets."
    },
    {
        "id": "OUT-029",
        "name": "Short Kurta",
        "category": "Kurtas",
        "rentPrice": 449,
        "securityDeposit": 300,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&q=80",
        "description": "Hip-length casual short kurta designed for pairing with jeans or tailored trousers.",
        "size": "38 (S)",
        "chestSize": "38\"",
        "waistSize": "32\"",
        "fitType": "Slim Fit",
        "color": "Rust Orange Silk Blend",
        "includedAccessories": [],
        "marketRetailPrice": 3000,
        "marketDemand": "High",
        "marketTrendNote": "Hip-length casual short kurta for pairing with jeans or trousers."
    },
    {
        "id": "OUT-030",
        "name": "Long Kurta",
        "category": "Kurtas",
        "rentPrice": 649,
        "securityDeposit": 400,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=800&q=80",
        "description": "Traditional ankle-reaching long silk kurta in ivory with subtle self-weaving texture.",
        "size": "44 (XL)",
        "chestSize": "44\"",
        "waistSize": "38\"",
        "fitType": "Regular Fit",
        "color": "Ivory Textured Silk",
        "includedAccessories": [
            "Churidar"
        ],
        "marketRetailPrice": 5000,
        "marketDemand": "Moderate",
        "marketTrendNote": "Traditional ankle-reaching long silk kurta in ivory."
    },
    {
        "id": "OUT-031",
        "name": "Asymmetric Kurta",
        "category": "Kurtas",
        "rentPrice": 999,
        "securityDeposit": 700,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&q=80",
        "description": "High-low diagonal hemline kurta featuring side overlap button placement and mandarin collar.",
        "size": "40 (M)",
        "chestSize": "40\"",
        "waistSize": "34\"",
        "fitType": "Slim Fit",
        "color": "Navy & Gold Accent",
        "includedAccessories": [
            "Slim Trousers"
        ],
        "marketRetailPrice": 8000,
        "marketDemand": "Trending",
        "marketTrendNote": "High-low diagonal hemline kurta featuring side overlap button."
    },
    {
        "id": "OUT-032",
        "name": "Cowl Kurta",
        "category": "Kurtas",
        "rentPrice": 1099,
        "securityDeposit": 750,
        "status": "rented",
        "imageUrl": "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&q=80",
        "description": "Draped front waterfall cowl neck kurta in soft georgette silk for Sangeet night flair.",
        "size": "38 (S)",
        "chestSize": "38\"",
        "waistSize": "32\"",
        "fitType": "Slim Fit",
        "color": "Rose Gold Georgette Silk",
        "includedAccessories": [
            "Churidar"
        ],
        "marketRetailPrice": 8500,
        "marketDemand": "High",
        "marketTrendNote": "Draped front waterfall cowl neck kurta in soft georgette silk."
    },
    {
        "id": "OUT-033",
        "name": "Angrakha Kurta",
        "category": "Kurtas",
        "rentPrice": 1299,
        "securityDeposit": 850,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?w=800&q=80",
        "description": "Royal Rajasthani crossover chest tie Angrakha style kurta with tassel drawstrings and gota lace.",
        "size": "42 (L)",
        "chestSize": "42\"",
        "waistSize": "36\"",
        "fitType": "Royal Tailored",
        "color": "Maroon & Gota Patti",
        "includedAccessories": [
            "Fabric Tassels",
            "Dhoti Pants"
        ],
        "marketRetailPrice": 10000,
        "marketDemand": "Classic Peak",
        "marketTrendNote": "Royal Rajasthani crossover chest tie Angrakha style kurta."
    },
    {
        "id": "OUT-034",
        "name": "Kurta Pajama",
        "category": "Kurta Sets",
        "rentPrice": 799,
        "securityDeposit": 500,
        "status": "maintenance",
        "imageUrl": "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=800&q=80",
        "description": "Classic 2-piece solid silk kurta paired with matching soft cotton pajama pants.",
        "size": "40 (M)",
        "chestSize": "40\"",
        "waistSize": "34\"",
        "fitType": "Regular Fit",
        "color": "Cream Silk & White Pajama",
        "includedAccessories": [
            "Cotton Pajama"
        ],
        "marketRetailPrice": 6500,
        "marketDemand": "High",
        "marketTrendNote": "Classic 2-piece solid silk kurta paired with cotton pajama."
    },
    {
        "id": "OUT-035",
        "name": "Kurta Churidar",
        "category": "Kurta Sets",
        "rentPrice": 899,
        "securityDeposit": 600,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?w=800&q=80",
        "description": "Tailored royal silk kurta with gathered ankle Churidar leggings for traditional silhouette.",
        "size": "40 (M)",
        "chestSize": "40\"",
        "waistSize": "34\"",
        "fitType": "Regular Fit",
        "color": "Emerald Silk & Churidar",
        "includedAccessories": [
            "Matching Churidar"
        ],
        "marketRetailPrice": 7500,
        "marketDemand": "High",
        "marketTrendNote": "Tailored royal silk kurta with gathered ankle Churidar."
    },
    {
        "id": "OUT-036",
        "name": "Kurta Dhoti Set",
        "category": "Kurta Sets",
        "rentPrice": 1199,
        "securityDeposit": 800,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1610189019599-3e0fa1c2a8a2?w=800&q=80",
        "description": "Festive silk kurta paired with pre-pleated ready-to-wear silk Dhoti pants.",
        "size": "42 (L)",
        "chestSize": "42\"",
        "waistSize": "36\"",
        "fitType": "Regular Fit",
        "color": "Yellow Silk & Gold Dhoti",
        "includedAccessories": [
            "Pre-pleated Dhoti Pants"
        ],
        "marketRetailPrice": 10000,
        "marketDemand": "Very High",
        "marketTrendNote": "Festive silk kurta paired with pre-pleated Dhoti pants."
    },
    {
        "id": "OUT-037",
        "name": "Kurta Jacket Set",
        "category": "Kurta Sets",
        "rentPrice": 1499,
        "securityDeposit": 1000,
        "status": "rented",
        "imageUrl": "https://images.unsplash.com/photo-1610189019599-3e0fa1c2a8a2?w=800&q=80",
        "description": "3-piece ensemble featuring silk kurta, pajama, and contrasting woven Nehru waistcoat jacket.",
        "size": "40 (M)",
        "chestSize": "40\"",
        "waistSize": "34\"",
        "fitType": "Regular Fit",
        "color": "Peach Silk & Floral Jacket",
        "includedAccessories": [
            "Matching Nehru Jacket",
            "Pocket Square"
        ],
        "marketRetailPrice": 12500,
        "marketDemand": "Very High",
        "marketTrendNote": "3-piece ensemble featuring silk kurta, pajama, and Nehru jacket."
    },
    {
        "id": "OUT-038",
        "name": "Kurta Palazzo Set",
        "category": "Kurta Sets",
        "rentPrice": 1099,
        "securityDeposit": 700,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=800&q=80",
        "description": "Modern comfort-fit wide-leg palazzo pants paired with embroidered straight cut kurta.",
        "size": "38 (S)",
        "chestSize": "38\"",
        "waistSize": "32\"",
        "fitType": "Slim Fit",
        "color": "Mint Green Silk & Palazzo",
        "includedAccessories": [
            "Palazzo Pants"
        ],
        "marketRetailPrice": 8500,
        "marketDemand": "Trending",
        "marketTrendNote": "Modern comfort-fit wide-leg palazzo pants with embroidered kurta."
    },
    {
        "id": "OUT-039",
        "name": "Kurta with Nehru Jacket",
        "category": "Kurta Sets",
        "rentPrice": 1399,
        "securityDeposit": 900,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1610189019599-3e0fa1c2a8a2?w=800&q=80",
        "description": "Royal cream kurta set with a vibrant digital floral silk Nehru jacket and brooch.",
        "size": "42 (L)",
        "chestSize": "42\"",
        "waistSize": "36\"",
        "fitType": "Regular Fit",
        "color": "Royal Cream & Rose Jacket",
        "includedAccessories": [
            "Nehru Jacket",
            "Designer Brooch"
        ],
        "marketRetailPrice": 11500,
        "marketDemand": "Very High",
        "marketTrendNote": "Royal cream kurta set with digital floral silk Nehru jacket."
    },
    {
        "id": "OUT-040",
        "name": "Nehru Jacket",
        "category": "Jackets",
        "rentPrice": 699,
        "securityDeposit": 500,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1610189019599-3e0fa1c2a8a2?w=800&q=80",
        "description": "Classic sleeveless mandarin collar Nehru waistcoat jacket in banarasi woven jacquard.",
        "size": "40 (M)",
        "chestSize": "40\"",
        "waistSize": "34\"",
        "fitType": "Regular Fit",
        "color": "Golden Jacquard Weave",
        "includedAccessories": [
            "Pocket Square"
        ],
        "marketRetailPrice": 5500,
        "marketDemand": "High",
        "marketTrendNote": "Sleeveless mandarin collar Nehru waistcoat in banarasi jacquard."
    },
    {
        "id": "OUT-041",
        "name": "Modi Jacket",
        "category": "Jackets",
        "rentPrice": 749,
        "securityDeposit": 500,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1617922001439-4a2e6562f328?w=800&q=80",
        "description": "Structured wool-blend Modi vest jacket with pocket square slit and fabric-covered buttons.",
        "size": "40 (M)",
        "chestSize": "40\"",
        "waistSize": "34\"",
        "fitType": "Slim Fit",
        "color": "Charcoal Wool Blend",
        "includedAccessories": [
            "Fabric Pocket Square"
        ],
        "marketRetailPrice": 6000,
        "marketDemand": "High",
        "marketTrendNote": "Structured wool-blend Modi vest jacket with pocket square slit."
    },
    {
        "id": "OUT-042",
        "name": "Printed Jacket",
        "category": "Jackets",
        "rentPrice": 899,
        "securityDeposit": 600,
        "status": "rented",
        "imageUrl": "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=800&q=80",
        "description": "Bold tropical floral printed silk waistcoat jacket for Mehendi & poolside wedding functions.",
        "size": "38 (S)",
        "chestSize": "38\"",
        "waistSize": "32\"",
        "fitType": "Slim Fit",
        "color": "Multi-color Floral Silk",
        "includedAccessories": [
            "Silk Pocket Square"
        ],
        "marketRetailPrice": 7000,
        "marketDemand": "Trending",
        "marketTrendNote": "Bold tropical floral printed silk waistcoat jacket."
    },
    {
        "id": "OUT-043",
        "name": "Embroidered Jacket",
        "category": "Jackets",
        "rentPrice": 1199,
        "securityDeposit": 800,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1610189019599-3e0fa1c2a8a2?w=800&q=80",
        "description": "Heavily hand-embroidered velvet waistcoat featuring gold zari motifs along collar and chest.",
        "size": "42 (L)",
        "chestSize": "42\"",
        "waistSize": "36\"",
        "fitType": "Regular Fit",
        "color": "Royal Maroon Velvet",
        "includedAccessories": [
            "Golden Brooch"
        ],
        "marketRetailPrice": 9500,
        "marketDemand": "High",
        "marketTrendNote": "Hand-embroidered velvet waistcoat featuring gold zari motifs."
    },
    {
        "id": "OUT-044",
        "name": "Silk Jacket",
        "category": "Jackets",
        "rentPrice": 999,
        "securityDeposit": 700,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1610189019599-3e0fa1c2a8a2?w=800&q=80",
        "description": "Pure raw silk sleeveless jacket in rich emerald tone with metallic button details.",
        "size": "40 (M)",
        "chestSize": "40\"",
        "waistSize": "34\"",
        "fitType": "Regular Fit",
        "color": "Deep Emerald Raw Silk",
        "includedAccessories": [
            "Metallic Buttons"
        ],
        "marketRetailPrice": 8000,
        "marketDemand": "High",
        "marketTrendNote": "Pure raw silk sleeveless jacket in rich emerald tone."
    },
    {
        "id": "OUT-045",
        "name": "Velvet Jacket",
        "category": "Jackets",
        "rentPrice": 1299,
        "securityDeposit": 850,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&q=80",
        "description": "Luxurious micro-velvet open waist jacket with satin lapel trim for evening celebrations.",
        "size": "42 (L)",
        "chestSize": "42\"",
        "waistSize": "36\"",
        "fitType": "Slim Fit",
        "color": "Black Micro-Velvet",
        "includedAccessories": [
            "Satin Lapel Pin"
        ],
        "marketRetailPrice": 10000,
        "marketDemand": "Trending",
        "marketTrendNote": "Micro-velvet open waist jacket with satin lapel trim."
    },
    {
        "id": "OUT-046",
        "name": "Waistcoat",
        "category": "Jackets",
        "rentPrice": 599,
        "securityDeposit": 400,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1617922001439-4a2e6562f328?w=800&q=80",
        "description": "Formal tailored ethnic waistcoat with adjustable back belt strap and sleek welt pockets.",
        "size": "38 (S)",
        "chestSize": "38\"",
        "waistSize": "32\"",
        "fitType": "Slim Fit",
        "color": "Classic Grey Jacquard",
        "includedAccessories": [],
        "marketRetailPrice": 4500,
        "marketDemand": "High",
        "marketTrendNote": "Formal tailored ethnic waistcoat with adjustable back belt."
    },
    {
        "id": "OUT-047",
        "name": "Ethnic Jacket",
        "category": "Jackets",
        "rentPrice": 949,
        "securityDeposit": 600,
        "status": "rented",
        "imageUrl": "https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?w=800&q=80",
        "description": "Traditional mirror-work embroidered ethnic jacket suitable for Garba & Navratri festival nights.",
        "size": "40 (M)",
        "chestSize": "40\"",
        "waistSize": "34\"",
        "fitType": "Regular Fit",
        "color": "Navy & Mirror Work",
        "includedAccessories": [
            "Mirror Work Pin"
        ],
        "marketRetailPrice": 7500,
        "marketDemand": "High",
        "marketTrendNote": "Mirror-work embroidered ethnic jacket suitable for Garba & Navratri."
    },
    {
        "id": "OUT-048",
        "name": "Pathani Suit",
        "category": "Pathani Wear",
        "rentPrice": 1199,
        "securityDeposit": 800,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?w=800&q=80",
        "description": "Classic 2-piece solid linen Pathani kurta suit with shirt collar, chest flaps, and gathered salwar pants.",
        "size": "42 (L)",
        "chestSize": "42\"",
        "waistSize": "36\"",
        "fitType": "Regular Fit",
        "color": "Jet Black Linen Blend",
        "includedAccessories": [
            "Pathani Salwar Pants"
        ],
        "marketRetailPrice": 8500,
        "marketDemand": "High",
        "marketTrendNote": "Classic 2-piece solid linen Pathani kurta suit with chest flaps."
    },
    {
        "id": "OUT-049",
        "name": "Pathani Kurta",
        "category": "Pathani Wear",
        "rentPrice": 799,
        "securityDeposit": 500,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?w=800&q=80",
        "description": "Heavy cotton Pathani kurta with shoulder tabs and cuffed sleeves in deep olive green.",
        "size": "40 (M)",
        "chestSize": "40\"",
        "waistSize": "34\"",
        "fitType": "Regular Fit",
        "color": "Olive Green Heavy Cotton",
        "includedAccessories": [],
        "marketRetailPrice": 5500,
        "marketDemand": "Moderate",
        "marketTrendNote": "Heavy cotton Pathani kurta with shoulder tabs in olive green."
    },
    {
        "id": "OUT-050",
        "name": "Pathani Salwar Set",
        "category": "Pathani Wear",
        "rentPrice": 1299,
        "securityDeposit": 850,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?w=800&q=80",
        "description": "Royal Afghan style voluminous salwar paired with heavy raw silk Pathani tunic.",
        "size": "44 (XL)",
        "chestSize": "44\"",
        "waistSize": "38\"",
        "fitType": "Regular Fit",
        "color": "Royal White Silk-Cotton",
        "includedAccessories": [
            "Voluminous Salwar"
        ],
        "marketRetailPrice": 9000,
        "marketDemand": "High",
        "marketTrendNote": "Royal Afghan style voluminous salwar with raw silk tunic."
    },
    {
        "id": "OUT-051",
        "name": "Pathani with Jacket",
        "category": "Pathani Wear",
        "rentPrice": 1699,
        "securityDeposit": 1100,
        "status": "maintenance",
        "imageUrl": "https://images.unsplash.com/photo-1610189019599-3e0fa1c2a8a2?w=800&q=80",
        "description": "3-piece Pathani suit layered with contrasting embroidered ethnic waist jacket.",
        "size": "42 (L)",
        "chestSize": "42\"",
        "waistSize": "36\"",
        "fitType": "Regular Fit",
        "color": "Maroon & Woven Vest",
        "includedAccessories": [
            "Matching Ethnic Vest",
            "Salwar"
        ],
        "marketRetailPrice": 12000,
        "marketDemand": "Trending",
        "marketTrendNote": "3-piece Pathani suit layered with embroidered waist jacket."
    },
    {
        "id": "OUT-052",
        "name": "Churidar",
        "category": "Bottom Wear",
        "rentPrice": 249,
        "securityDeposit": 200,
        "status": "rented",
        "imageUrl": "https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?w=800&q=80",
        "description": "Elasticated waistband cotton-lycra stretchable Churidar pants with classic ankle gathers.",
        "size": "Free Size",
        "chestSize": "36\"",
        "waistSize": "32\"",
        "fitType": "Slim Fit",
        "color": "Off-White Stretch Cotton",
        "includedAccessories": [],
        "marketRetailPrice": 1500,
        "marketDemand": "High",
        "marketTrendNote": "Elasticated cotton-lycra stretchable Churidar pants."
    },
    {
        "id": "OUT-053",
        "name": "Pajama",
        "category": "Bottom Wear",
        "rentPrice": 199,
        "securityDeposit": 150,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=800&q=80",
        "description": "Straight-cut soft breathable white cotton Pajama pants with drawstring waist.",
        "size": "Free Size",
        "chestSize": "36\"",
        "waistSize": "34\"",
        "fitType": "Regular Fit",
        "color": "Pure White Cotton",
        "includedAccessories": [],
        "marketRetailPrice": 1200,
        "marketDemand": "High",
        "marketTrendNote": "Straight-cut white cotton pajama pants with drawstring waist."
    },
    {
        "id": "OUT-054",
        "name": "Dhoti",
        "category": "Bottom Wear",
        "rentPrice": 349,
        "securityDeposit": 250,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&q=80",
        "description": "Traditional unstitched white silk Dhoti with gold zari border (Zari Veshti).",
        "size": "Free Size",
        "chestSize": "36\"",
        "waistSize": "34\"",
        "fitType": "Regular Fit",
        "color": "Cream & Gold Zari",
        "includedAccessories": [],
        "marketRetailPrice": 2200,
        "marketDemand": "Moderate",
        "marketTrendNote": "Traditional unstitched white silk Dhoti with gold zari border."
    },
    {
        "id": "OUT-055",
        "name": "Dhoti Pants",
        "category": "Bottom Wear",
        "rentPrice": 449,
        "securityDeposit": 300,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1610189019599-3e0fa1c2a8a2?w=800&q=80",
        "description": "Pre-stitched draped Dhoti pants featuring pleats and elastic waistband for instant hassle-free wear.",
        "size": "M/L",
        "chestSize": "36\"",
        "waistSize": "34\"",
        "fitType": "Slim Fit",
        "color": "Golden Silk Blend",
        "includedAccessories": [],
        "marketRetailPrice": 2800,
        "marketDemand": "High",
        "marketTrendNote": "Pre-stitched draped Dhoti pants featuring pleats and elastic waist."
    },
    {
        "id": "OUT-056",
        "name": "Aligarhi Pants",
        "category": "Bottom Wear",
        "rentPrice": 299,
        "securityDeposit": 200,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1617922001439-4a2e6562f328?w=800&q=80",
        "description": "Tapered ankle Aligarhi pajama pants crafted from crisp cotton silk fabric.",
        "size": "M/L",
        "chestSize": "36\"",
        "waistSize": "34\"",
        "fitType": "Slim Fit",
        "color": "Ivory Cotton-Silk",
        "includedAccessories": [],
        "marketRetailPrice": 1800,
        "marketDemand": "High",
        "marketTrendNote": "Tapered ankle Aligarhi pajama pants in cotton silk."
    },
    {
        "id": "OUT-057",
        "name": "Salwar",
        "category": "Bottom Wear",
        "rentPrice": 299,
        "securityDeposit": 200,
        "status": "rented",
        "imageUrl": "https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?w=800&q=80",
        "description": "Pleated voluminous Salwar bottom with gathered cuffs for authentic Punjabi & Pathani fit.",
        "size": "Free Size",
        "chestSize": "36\"",
        "waistSize": "34\"",
        "fitType": "Regular Fit",
        "color": "Black Cotton",
        "includedAccessories": [],
        "marketRetailPrice": 1800,
        "marketDemand": "Moderate",
        "marketTrendNote": "Pleated voluminous Salwar bottom with gathered cuffs."
    },
    {
        "id": "OUT-058",
        "name": "Patiala",
        "category": "Bottom Wear",
        "rentPrice": 399,
        "securityDeposit": 250,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?w=800&q=80",
        "description": "Heavy pleat Punjabi Patiala salwar bottom designed for traditional festive wear.",
        "size": "Free Size",
        "chestSize": "36\"",
        "waistSize": "34\"",
        "fitType": "Regular Fit",
        "color": "Royal White Silk",
        "includedAccessories": [],
        "marketRetailPrice": 2200,
        "marketDemand": "High",
        "marketTrendNote": "Heavy pleat Punjabi Patiala salwar bottom."
    },
    {
        "id": "OUT-059",
        "name": "Straight Pants",
        "category": "Bottom Wear",
        "rentPrice": 349,
        "securityDeposit": 250,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&q=80",
        "description": "Tailored trouser-fit straight cotton-silk pants with side pockets.",
        "size": "32/34",
        "chestSize": "36\"",
        "waistSize": "32\"",
        "fitType": "Slim Fit",
        "color": "Beige Silk Blend",
        "includedAccessories": [],
        "marketRetailPrice": 2000,
        "marketDemand": "High",
        "marketTrendNote": "Tailored trouser-fit straight cotton-silk pants."
    },
    {
        "id": "OUT-060",
        "name": "Trouser",
        "category": "Bottom Wear",
        "rentPrice": 399,
        "securityDeposit": 250,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&q=80",
        "description": "Formal slim-fit flat front trousers with belt loops and buttoned rear pockets.",
        "size": "34 Waist",
        "chestSize": "36\"",
        "waistSize": "34\"",
        "fitType": "Slim Fit",
        "color": "Navy Wool-Poly",
        "includedAccessories": [],
        "marketRetailPrice": 2500,
        "marketDemand": "High",
        "marketTrendNote": "Formal slim-fit flat front trousers with belt loops."
    },
    {
        "id": "OUT-061",
        "name": "Ethnic Pant",
        "category": "Bottom Wear",
        "rentPrice": 349,
        "securityDeposit": 250,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1610189019599-3e0fa1c2a8a2?w=800&q=80",
        "description": "Textured jacquard ethnic pants with subtle self-pattern matching modern kurtas.",
        "size": "34 Waist",
        "chestSize": "36\"",
        "waistSize": "34\"",
        "fitType": "Slim Fit",
        "color": "Champagne Jacquard",
        "includedAccessories": [],
        "marketRetailPrice": 2200,
        "marketDemand": "High",
        "marketTrendNote": "Textured jacquard ethnic pants matching short kurtas."
    },
    {
        "id": "OUT-062",
        "name": "Traditional Dhoti",
        "category": "Dhoti Collection",
        "rentPrice": 499,
        "securityDeposit": 300,
        "status": "rented",
        "imageUrl": "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&q=80",
        "description": "Handcrafted pure cotton traditional Dhoti featuring red and gold temple zari borders.",
        "size": "Free Size",
        "chestSize": "36\"",
        "waistSize": "34\"",
        "fitType": "Regular Fit",
        "color": "White & Red Temple Border",
        "includedAccessories": [
            "Angavastram Stole"
        ],
        "marketRetailPrice": 3500,
        "marketDemand": "Moderate",
        "marketTrendNote": "Pure cotton traditional Dhoti featuring red and gold temple zari borders."
    },
    {
        "id": "OUT-063",
        "name": "Silk Dhoti",
        "category": "Dhoti Collection",
        "rentPrice": 799,
        "securityDeposit": 500,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1610189019599-3e0fa1c2a8a2?w=800&q=80",
        "description": "Luminous Kanchipuram art silk Dhoti in cream with heavy golden woven border.",
        "size": "Free Size",
        "chestSize": "36\"",
        "waistSize": "34\"",
        "fitType": "Regular Fit",
        "color": "Cream & Heavy Gold Zari",
        "includedAccessories": [
            "Silk Angavastram"
        ],
        "marketRetailPrice": 5500,
        "marketDemand": "High",
        "marketTrendNote": "Kanchipuram art silk Dhoti with heavy golden woven border."
    },
    {
        "id": "OUT-064",
        "name": "Cotton Dhoti",
        "category": "Dhoti Collection",
        "rentPrice": 399,
        "securityDeposit": 250,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&q=80",
        "description": "Lightweight 100% combed cotton Dhoti for ritual ceremonies and temple visits.",
        "size": "Free Size",
        "chestSize": "36\"",
        "waistSize": "34\"",
        "fitType": "Regular Fit",
        "color": "Pure White Combed Cotton",
        "includedAccessories": [],
        "marketRetailPrice": 2500,
        "marketDemand": "High",
        "marketTrendNote": "Lightweight 100% combed cotton Dhoti for ritual ceremonies."
    },
    {
        "id": "OUT-065",
        "name": "Dhoti Kurta Set",
        "category": "Dhoti Collection",
        "rentPrice": 1399,
        "securityDeposit": 900,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1617922001439-4a2e6562f328?w=800&q=80",
        "description": "Premium festive silk Kurta matched with pre-pleated Dhoti pants and matching pocket brooch.",
        "size": "40 (M)",
        "chestSize": "40\"",
        "waistSize": "34\"",
        "fitType": "Regular Fit",
        "color": "Maroon Silk & Gold Dhoti",
        "includedAccessories": [
            "Pre-pleated Dhoti",
            "Pocket Brooch"
        ],
        "marketRetailPrice": 11000,
        "marketDemand": "Very High",
        "marketTrendNote": "Festive silk Kurta matched with pre-pleated Dhoti pants."
    },
    {
        "id": "OUT-066",
        "name": "Dhoti Sherwani Set",
        "category": "Dhoti Collection",
        "rentPrice": 3499,
        "securityDeposit": 2200,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&q=80",
        "description": "Designer groom Sherwani paired with royal pleated Dhoti pants instead of churidar.",
        "size": "42 (L)",
        "chestSize": "42\"",
        "waistSize": "36\"",
        "fitType": "Royal Tailored",
        "color": "Ivory Royal Silk & Dhoti",
        "includedAccessories": [
            "Royal Safa",
            "Dhoti Pants",
            "Dupatta"
        ],
        "marketRetailPrice": 28000,
        "marketDemand": "Trending",
        "marketTrendNote": "Groom Sherwani paired with royal pleated Dhoti pants."
    },
    {
        "id": "OUT-067",
        "name": "Dhoti with Angavastram",
        "category": "Dhoti Collection",
        "rentPrice": 899,
        "securityDeposit": 600,
        "status": "rented",
        "imageUrl": "https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?w=800&q=80",
        "description": "South Indian traditional Veshti Dhoti ensemble paired with matching golden border Angavastram shoulder drape.",
        "size": "Free Size",
        "chestSize": "40\"",
        "waistSize": "34\"",
        "fitType": "Regular Fit",
        "color": "Gold Mayilkan Silk",
        "includedAccessories": [
            "Gold Border Angavastram"
        ],
        "marketRetailPrice": 6500,
        "marketDemand": "High",
        "marketTrendNote": "South Indian Veshti Dhoti ensemble paired with Angavastram."
    },
    {
        "id": "OUT-068",
        "name": "Blazer",
        "category": "Formal / Occasion Wear",
        "rentPrice": 1499,
        "securityDeposit": 1000,
        "status": "maintenance",
        "imageUrl": "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&q=80",
        "description": "Single-breasted slim-fit navy blazer crafted from fine Italian wool blend.",
        "size": "40 (M)",
        "chestSize": "40\"",
        "waistSize": "34\"",
        "fitType": "Slim Fit",
        "color": "Navy Blue Fine Wool",
        "includedAccessories": [
            "Silk Pocket Square"
        ],
        "marketRetailPrice": 12000,
        "marketDemand": "High",
        "marketTrendNote": "Single-breasted slim-fit navy blazer from fine wool blend."
    },
    {
        "id": "OUT-069",
        "name": "Tuxedo",
        "category": "Formal / Occasion Wear",
        "rentPrice": 2799,
        "securityDeposit": 1800,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&q=80",
        "description": "Black-tie luxury satin peak lapel tuxedo jacket, cummerbund, bow tie, and formal pants.",
        "size": "40 (M)",
        "chestSize": "40\"",
        "waistSize": "33\"",
        "fitType": "Slim Fit",
        "color": "Jet Black Satin Peak Lapel",
        "includedAccessories": [
            "Silk Bow Tie",
            "Cummerbund",
            "Silver Studs"
        ],
        "marketRetailPrice": 22000,
        "marketDemand": "Very High",
        "marketTrendNote": "Black-tie luxury satin peak lapel tuxedo jacket with cummerbund."
    },
    {
        "id": "OUT-070",
        "name": "Three-Piece Suit",
        "category": "Formal / Occasion Wear",
        "rentPrice": 2299,
        "securityDeposit": 1500,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1617922001439-4a2e6562f328?w=800&q=80",
        "description": "Formal 3-piece suit including notch lapel jacket, double-breasted waistcoat, and trousers.",
        "size": "42 (L)",
        "chestSize": "42\"",
        "waistSize": "36\"",
        "fitType": "Slim Fit",
        "color": "Charcoal Grey & Black Vest",
        "includedAccessories": [
            "Matching Vest",
            "Formal Tie",
            "Pocket Square"
        ],
        "marketRetailPrice": 18000,
        "marketDemand": "High",
        "marketTrendNote": "Formal 3-piece suit including notch lapel jacket and waistcoat."
    },
    {
        "id": "OUT-071",
        "name": "Two-Piece Suit",
        "category": "Formal / Occasion Wear",
        "rentPrice": 1799,
        "securityDeposit": 1200,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&q=80",
        "description": "Modern charcoal grey 2-piece suit for corporate galas and formal wedding receptions.",
        "size": "40 (M)",
        "chestSize": "40\"",
        "waistSize": "34\"",
        "fitType": "Regular Fit",
        "color": "Midnight Black Fine Wool",
        "includedAccessories": [
            "Formal Tie",
            "Pocket Square"
        ],
        "marketRetailPrice": 14000,
        "marketDemand": "High",
        "marketTrendNote": "Modern charcoal grey 2-piece suit for corporate galas."
    },
    {
        "id": "OUT-072",
        "name": "Dinner Jacket",
        "category": "Formal / Occasion Wear",
        "rentPrice": 1999,
        "securityDeposit": 1300,
        "status": "rented",
        "imageUrl": "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&q=80",
        "description": "Velvet shawl lapel dinner jacket in burgundy red with satin buttons.",
        "size": "40 (M)",
        "chestSize": "40\"",
        "waistSize": "34\"",
        "fitType": "Slim Fit",
        "color": "Burgundy Velvet & Satin",
        "includedAccessories": [
            "Black Bow Tie",
            "Pocket Square"
        ],
        "marketRetailPrice": 15000,
        "marketDemand": "Trending",
        "marketTrendNote": "Velvet shawl lapel dinner jacket in burgundy red."
    },
    {
        "id": "OUT-073",
        "name": "Waistcoat Set",
        "category": "Formal / Occasion Wear",
        "rentPrice": 1299,
        "securityDeposit": 850,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1617922001439-4a2e6562f328?w=800&q=80",
        "description": "Tailored 3-piece formal waistcoat ensemble with dress shirt, silk tie, and formal trousers.",
        "size": "38 (S)",
        "chestSize": "38\"",
        "waistSize": "32\"",
        "fitType": "Slim Fit",
        "color": "Grey Tweed & White Shirt",
        "includedAccessories": [
            "Dress Shirt",
            "Silk Tie",
            "Formal Trousers"
        ],
        "marketRetailPrice": 9500,
        "marketDemand": "High",
        "marketTrendNote": "3-piece formal waistcoat ensemble with dress shirt & tie."
    },
    {
        "id": "OUT-074",
        "name": "Formal Suit",
        "category": "Formal / Occasion Wear",
        "rentPrice": 1899,
        "securityDeposit": 1200,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&q=80",
        "description": "Executive navy blue pinstripe formal suit crafted for black-tie receptions and awards nights.",
        "size": "42 (L)",
        "chestSize": "42\"",
        "waistSize": "36\"",
        "fitType": "Regular Fit",
        "color": "Navy Pinstripe Fine Poly-Wool",
        "includedAccessories": [
            "Silk Tie",
            "Pocket Square"
        ],
        "marketRetailPrice": 15000,
        "marketDemand": "High",
        "marketTrendNote": "Executive navy pinstripe formal suit for black-tie events."
    },
    {
        "id": "OUT-075",
        "name": "Groom Sherwani",
        "category": "Wedding Collection",
        "rentPrice": 5999,
        "securityDeposit": 4000,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&q=80",
        "description": "Ultimate royal groom wedding sherwani in ivory silk featuring hand-carved zardozi and real pearl work.",
        "size": "42 (L)",
        "chestSize": "42\"",
        "waistSize": "36\"",
        "fitType": "Royal Tailored",
        "color": "Ivory Raw Silk & Real Pearl",
        "includedAccessories": [
            "Royal Turban (Safa)",
            "Embroidered Dupatta",
            "Pearl Mala",
            "Kalgi Pin",
            "Brooch"
        ],
        "marketRetailPrice": 55000,
        "marketDemand": "Very High",
        "marketTrendNote": "Royal groom wedding sherwani in ivory silk with real pearl work."
    },
    {
        "id": "OUT-076",
        "name": "Reception Suit",
        "category": "Wedding Collection",
        "rentPrice": 3499,
        "securityDeposit": 2200,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&q=80",
        "description": "Midnight black velvet-lapel reception tux suit tailored with sleek satin piping and cufflinks.",
        "size": "40 (M)",
        "chestSize": "40\"",
        "waistSize": "34\"",
        "fitType": "Slim Fit",
        "color": "Midnight Black & Satin Piping",
        "includedAccessories": [
            "Satin Bow Tie",
            "Cufflinks",
            "Pocket Square"
        ],
        "marketRetailPrice": 28000,
        "marketDemand": "High",
        "marketTrendNote": "Midnight black velvet-lapel reception tux suit."
    },
    {
        "id": "OUT-077",
        "name": "Engagement Indo-Western",
        "category": "Wedding Collection",
        "rentPrice": 3799,
        "securityDeposit": 2500,
        "status": "rented",
        "imageUrl": "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&q=80",
        "description": "Rose gold and pastel mint asymmetric Indo-Western set for engagement Ring Ceremony night.",
        "size": "40 (M)",
        "chestSize": "40\"",
        "waistSize": "34\"",
        "fitType": "Slim Fit",
        "color": "Rose Gold & Pastel Mint",
        "includedAccessories": [
            "Metallic Lapel Pin",
            "Slim Trousers"
        ],
        "marketRetailPrice": 30000,
        "marketDemand": "Very High",
        "marketTrendNote": "Rose gold & mint asymmetric Indo-Western set for Ring Ceremony."
    },
    {
        "id": "OUT-078",
        "name": "Haldi Kurta Set",
        "category": "Wedding Collection",
        "rentPrice": 1199,
        "securityDeposit": 800,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1610189019599-3e0fa1c2a8a2?w=800&q=80",
        "description": "Vibrant sun yellow raw silk kurta with white cotton dhoti pants and bandhani pocket square.",
        "size": "40 (M)",
        "chestSize": "40\"",
        "waistSize": "34\"",
        "fitType": "Regular Fit",
        "color": "Sun Yellow Raw Silk",
        "includedAccessories": [
            "White Cotton Dhoti",
            "Bandhani Pocket Square"
        ],
        "marketRetailPrice": 8500,
        "marketDemand": "Very High",
        "marketTrendNote": "Sun yellow raw silk kurta with white cotton dhoti pants."
    },
    {
        "id": "OUT-079",
        "name": "Mehendi Kurta Set",
        "category": "Wedding Collection",
        "rentPrice": 1399,
        "securityDeposit": 900,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=800&q=80",
        "description": "Emerald green embroidered kurta with botanical floral jacket for Mehendi celebrations.",
        "size": "42 (L)",
        "chestSize": "42\"",
        "waistSize": "36\"",
        "fitType": "Regular Fit",
        "color": "Emerald Green & Botanical Jacket",
        "includedAccessories": [
            "Botanical Printed Jacket",
            "Silk Pajama"
        ],
        "marketRetailPrice": 9500,
        "marketDemand": "Very High",
        "marketTrendNote": "Emerald green embroidered kurta with botanical floral jacket."
    },
    {
        "id": "OUT-080",
        "name": "Sangeet Indo-Western",
        "category": "Wedding Collection",
        "rentPrice": 3899,
        "securityDeposit": 2500,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&q=80",
        "description": "Draped black mirror-work Indo-Western outfit designed for stage performance & Sangeet dance.",
        "size": "40 (M)",
        "chestSize": "40\"",
        "waistSize": "34\"",
        "fitType": "Slim Fit",
        "color": "Jet Black Mirror Work",
        "includedAccessories": [
            "Mirror Work Chain Brooch",
            "Cowl Kurta"
        ],
        "marketRetailPrice": 32000,
        "marketDemand": "Trending",
        "marketTrendNote": "Draped black mirror-work Indo-Western outfit for Sangeet stage."
    },
    {
        "id": "OUT-081",
        "name": "Baraat Sherwani",
        "category": "Wedding Collection",
        "rentPrice": 5499,
        "securityDeposit": 3500,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1610189019599-3e0fa1c2a8a2?w=800&q=80",
        "description": "Grand maroon velvet Baraat sherwani with gold thread work, matching safa, and ceremonial sword belt loop.",
        "size": "42 (L)",
        "chestSize": "42\"",
        "waistSize": "36\"",
        "fitType": "Royal Tailored",
        "color": "Royal Maroon Velvet & Gold",
        "includedAccessories": [
            "Royal Maroon Safa",
            "Ceremonial Sword Strap",
            "Gold Stole"
        ],
        "marketRetailPrice": 48000,
        "marketDemand": "Very High",
        "marketTrendNote": "Grand maroon velvet Baraat sherwani with gold thread work."
    },
    {
        "id": "OUT-082",
        "name": "Royal Wedding Set",
        "category": "Wedding Collection",
        "rentPrice": 6999,
        "securityDeposit": 4500,
        "status": "rented",
        "imageUrl": "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&q=80",
        "description": "Complete 8-piece groom master collection: Sherwani, Safa, Dupatta, Mala, Brooch, Mojari, Sword strap & Stole.",
        "size": "42 (L)",
        "chestSize": "42\"",
        "waistSize": "36\"",
        "fitType": "Royal Tailored",
        "color": "Imperial Antique Gold",
        "includedAccessories": [
            "Royal Turban (Safa)",
            "Embroidered Dupatta",
            "Pearl Necklace",
            "Kalgi",
            "Brooch",
            "Velvet Mojari",
            "Sword Strap"
        ],
        "marketRetailPrice": 65000,
        "marketDemand": "Very High",
        "marketTrendNote": "Complete 8-piece groom master collection: Sherwani, Safa, Dupatta & accessories."
    },
    {
        "id": "OUT-083",
        "name": "Gujarati Kediyu",
        "category": "Regional Traditional Wear",
        "rentPrice": 1399,
        "securityDeposit": 900,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?w=800&q=80",
        "description": "Traditional flared Gujarati Kediyu top with mirror work embroidery, tie-ups, and pleated Kafni salwar.",
        "size": "40 (M)",
        "chestSize": "40\"",
        "waistSize": "34\"",
        "fitType": "Regular Fit",
        "color": "Multi-Color Mirror Work",
        "includedAccessories": [
            "Kafni Salwar",
            "Tie-up Tassels"
        ],
        "marketRetailPrice": 10000,
        "marketDemand": "High",
        "marketTrendNote": "Flared Gujarati Kediyu top with mirror work & Kafni salwar."
    },
    {
        "id": "OUT-084",
        "name": "Rajasthani Angrakha",
        "category": "Regional Traditional Wear",
        "rentPrice": 1699,
        "securityDeposit": 1100,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?w=800&q=80",
        "description": "Authentic Royal Mewar overlapping Angrakha with hand-block bandhani print and gota patti trim.",
        "size": "42 (L)",
        "chestSize": "42\"",
        "waistSize": "36\"",
        "fitType": "Royal Tailored",
        "color": "Red & Bandhani Gold",
        "includedAccessories": [
            "Bandhani Safa",
            "Gota Stole"
        ],
        "marketRetailPrice": 12000,
        "marketDemand": "High",
        "marketTrendNote": "Royal Mewar overlapping Angrakha with gota patti trim."
    },
    {
        "id": "OUT-085",
        "name": "Maharashtrian Dhoti Kurta",
        "category": "Regional Traditional Wear",
        "rentPrice": 1299,
        "securityDeposit": 850,
        "status": "maintenance",
        "imageUrl": "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&q=80",
        "description": "Classic Maharashtrian yellow silk Kurta, Kashta style silk Dhoti, and traditional Pheta turban.",
        "size": "40 (M)",
        "chestSize": "40\"",
        "waistSize": "34\"",
        "fitType": "Regular Fit",
        "color": "Sun Yellow & Red Pheta",
        "includedAccessories": [
            "Marathi Pheta Turban",
            "Kashta Dhoti"
        ],
        "marketRetailPrice": 9500,
        "marketDemand": "High",
        "marketTrendNote": "Yellow silk Kurta, Kashta silk Dhoti, and Pheta turban."
    },
    {
        "id": "OUT-086",
        "name": "Bengali Dhoti Kurta",
        "category": "Regional Traditional Wear",
        "rentPrice": 1199,
        "securityDeposit": 800,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=800&q=80",
        "description": "Tussar silk cream Kurta paired with red border Gorod silk Dhoti, ideal for Durga Puja & wedding rituals.",
        "size": "40 (M)",
        "chestSize": "40\"",
        "waistSize": "34\"",
        "fitType": "Regular Fit",
        "color": "Cream Tussar & Red Border",
        "includedAccessories": [
            "Gorod Red Border Dhoti",
            "Uttariya Stole"
        ],
        "marketRetailPrice": 8500,
        "marketDemand": "High",
        "marketTrendNote": "Tussar silk cream Kurta paired with red Gorod border Dhoti."
    },
    {
        "id": "OUT-087",
        "name": "South Indian Veshti Set",
        "category": "Regional Traditional Wear",
        "rentPrice": 1099,
        "securityDeposit": 700,
        "status": "rented",
        "imageUrl": "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=800&q=80",
        "description": "Pure silk Mayilkan border Veshti Dhoti with matching full-sleeve silk shirt and Angavastram.",
        "size": "40 (M)",
        "chestSize": "40\"",
        "waistSize": "34\"",
        "fitType": "Regular Fit",
        "color": "Pure White & Gold Mayilkan",
        "includedAccessories": [
            "Silk Shirt",
            "Angavastram"
        ],
        "marketRetailPrice": 8000,
        "marketDemand": "High",
        "marketTrendNote": "Silk Mayilkan border Veshti with full-sleeve silk shirt."
    },
    {
        "id": "OUT-088",
        "name": "Punjabi Kurta Pajama",
        "category": "Regional Traditional Wear",
        "rentPrice": 1099,
        "securityDeposit": 700,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?w=800&q=80",
        "description": "Authentic Muktsari style Punjabi Kurta with broad cuff sleeves and loose pajama pants.",
        "size": "42 (L)",
        "chestSize": "42\"",
        "waistSize": "36\"",
        "fitType": "Regular Fit",
        "color": "Royal White Fine Cotton",
        "includedAccessories": [
            "Matching Loose Pajama"
        ],
        "marketRetailPrice": 7500,
        "marketDemand": "High",
        "marketTrendNote": "Muktsari style Punjabi Kurta with broad cuff sleeves."
    },
    {
        "id": "OUT-089",
        "name": "Kashmiri Phiran",
        "category": "Regional Traditional Wear",
        "rentPrice": 1499,
        "securityDeposit": 1000,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1610189019599-3e0fa1c2a8a2?w=800&q=80",
        "description": "Warm wool-cashmere Kashmiri Phiran cloak featuring intricate Aari floral needlework embroidery.",
        "size": "44 (XL)",
        "chestSize": "44\"",
        "waistSize": "38\"",
        "fitType": "Regular Fit",
        "color": "Deep Walnut Wool & Aari Embroidery",
        "includedAccessories": [
            "Embroidered Stole"
        ],
        "marketRetailPrice": 11000,
        "marketDemand": "Trending",
        "marketTrendNote": "Warm wool Kashmiri Phiran with Aari needlework embroidery."
    },
    {
        "id": "OUT-090",
        "name": "Lucknowi Kurta",
        "category": "Regional Traditional Wear",
        "rentPrice": 1399,
        "securityDeposit": 900,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?w=800&q=80",
        "description": "Pristine white georgette silk Lucknowi Chikankari kurta with intricate Bakhiya and Phanda thread embroidery.",
        "size": "40 (M)",
        "chestSize": "40\"",
        "waistSize": "34\"",
        "fitType": "Regular Fit",
        "color": "Pristine White Georgette",
        "includedAccessories": [
            "Silk Pajama",
            "Pearl Lapel Pin"
        ],
        "marketRetailPrice": 10000,
        "marketDemand": "Very High",
        "marketTrendNote": "Pristine white georgette silk Lucknowi Chikankari kurta."
    },
    {
        "id": "OUT-091",
        "name": "Velvet Sherwani (Premium Edition)",
        "category": "Premium Collection",
        "rentPrice": 6499,
        "securityDeposit": 4000,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&q=80",
        "description": "Ultra-luxury deep royal navy micro-velvet groom sherwani encrusted with genuine dabka and zardozi work.",
        "size": "42 (L)",
        "chestSize": "42\"",
        "waistSize": "36\"",
        "fitType": "Royal Tailored",
        "color": "Deep Royal Navy Velvet",
        "includedAccessories": [
            "Zardozi Velvet Dupatta",
            "Royal Safa",
            "Pearl Mala",
            "Kalgi"
        ],
        "marketRetailPrice": 58000,
        "marketDemand": "Very High",
        "marketTrendNote": "Ultra-luxury deep royal navy micro-velvet with dabka & zardozi."
    },
    {
        "id": "OUT-092",
        "name": "Designer Indo-Western (Premium Edition)",
        "category": "Premium Collection",
        "rentPrice": 5999,
        "securityDeposit": 3800,
        "status": "rented",
        "imageUrl": "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&q=80",
        "description": "High-fashion asymmetric draped layered Indo-Western with metallic bronze embroidery.",
        "size": "40 (M)",
        "chestSize": "40\"",
        "waistSize": "34\"",
        "fitType": "Slim Fit",
        "color": "Bronze & Charcoal Metallic",
        "includedAccessories": [
            "Designer Brooch",
            "Metallic Stole",
            "Slim Pants"
        ],
        "marketRetailPrice": 52000,
        "marketDemand": "Trending",
        "marketTrendNote": "Asymmetric draped layered Indo-Western with bronze embroidery."
    },
    {
        "id": "OUT-093",
        "name": "Zardozi Sherwani",
        "category": "Premium Collection",
        "rentPrice": 6999,
        "securityDeposit": 4500,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1610189019599-3e0fa1c2a8a2?w=800&q=80",
        "description": "Heavy Mughal-heritage Zardozi work gold sherwani with intricate hand-crafted copper and gold wire embroidery.",
        "size": "42 (L)",
        "chestSize": "42\"",
        "waistSize": "36\"",
        "fitType": "Royal Tailored",
        "color": "Antique Gold Silk & Copper Zari",
        "includedAccessories": [
            "Heavily Embroidered Dupatta",
            "Gold Safa",
            "Emerald Brooch"
        ],
        "marketRetailPrice": 65000,
        "marketDemand": "Very High",
        "marketTrendNote": "Heavy Mughal-heritage Zardozi work gold sherwani."
    },
    {
        "id": "OUT-094",
        "name": "Mirror Work Kurta",
        "category": "Premium Collection",
        "rentPrice": 1899,
        "securityDeposit": 1200,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?w=800&q=80",
        "description": "Premium real glass mirror-work silk kurta jacket set for high-profile Sangeet and festive night.",
        "size": "40 (M)",
        "chestSize": "40\"",
        "waistSize": "34\"",
        "fitType": "Regular Fit",
        "color": "Royal Blue & Real Glass Mirror",
        "includedAccessories": [
            "Mirror Work Jacket",
            "Silk Pajama"
        ],
        "marketRetailPrice": 14000,
        "marketDemand": "Very High",
        "marketTrendNote": "Real glass mirror-work silk kurta jacket set for Sangeet."
    },
    {
        "id": "OUT-095",
        "name": "Sequins Sherwani",
        "category": "Premium Collection",
        "rentPrice": 4999,
        "securityDeposit": 3200,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1617922001439-4a2e6562f328?w=800&q=80",
        "description": "Shimmering matte black self-sequin sherwani with subtle shine for night receptions.",
        "size": "40 (M)",
        "chestSize": "40\"",
        "waistSize": "34\"",
        "fitType": "Slim Fit",
        "color": "Matte Black & Sequin Shimmer",
        "includedAccessories": [
            "Black Sequin Dupatta",
            "Designer Brooch"
        ],
        "marketRetailPrice": 42000,
        "marketDemand": "Trending",
        "marketTrendNote": "Shimmering matte black self-sequin sherwani for night receptions."
    },
    {
        "id": "OUT-096",
        "name": "Hand Embroidered Sherwani",
        "category": "Premium Collection",
        "rentPrice": 5899,
        "securityDeposit": 3800,
        "status": "available",
        "imageUrl": "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&q=80",
        "description": "Master artisan hand-embroidered raw silk sherwani featuring 120 hours of intricate needle craftsmanship.",
        "size": "42 (L)",
        "chestSize": "42\"",
        "waistSize": "36\"",
        "fitType": "Royal Tailored",
        "color": "Ivory Raw Silk & Gold Thread",
        "includedAccessories": [
            "Hand-embroidered Stole",
            "Royal Turban"
        ],
        "marketRetailPrice": 50000,
        "marketDemand": "Very High",
        "marketTrendNote": "Master artisan hand-embroidered raw silk sherwani (120 hrs work)."
    },
    {
        "id": "OUT-097",
        "name": "Royal Bandhgala",
        "category": "Premium Collection",
        "rentPrice": 4499,
        "securityDeposit": 3000,
        "status": "rented",
        "imageUrl": "https://images.unsplash.com/photo-1617922001439-4a2e6562f328?w=800&q=80",
        "description": "Presidential velvet collar Bandhgala jacket with 24K gold plated crested brass buttons and silk trousers.",
        "size": "42 (L)",
        "chestSize": "42\"",
        "waistSize": "36\"",
        "fitType": "Regular Fit",
        "color": "Black Velvet Collar & Fine Wool",
        "includedAccessories": [
            "24K Gold Plated Buttons",
            "Silk Pocket Square"
        ],
        "marketRetailPrice": 38000,
        "marketDemand": "Classic Peak",
        "marketTrendNote": "Velvet collar Bandhgala jacket with 24K gold plated crested buttons."
    }
];

export const INITIAL_CUSTOMERS: Customer[] = [
    {
        id: 'CUST-001',
        name: 'Vikramaditya Rathore',
        initials: 'VR',
        avatarColor: 'linear-gradient(135deg, #3b82f6, #1d4ed8)',
        email: 'vikram.rathore@email.com',
        phone: '+91 98765 43210',
        location: 'Jaipur, Rajasthan',
        status: 'active',
        totalRentals: 8,
        totalSpent: 48500,
        joinDate: 'Jan 2025',
    },
    {
        id: 'CUST-002',
        name: 'Amanpreet Singh',
        initials: 'AS',
        avatarColor: 'linear-gradient(135deg, #a855f7, #7c3aed)',
        email: 'aman.singh@email.com',
        phone: '+91 98765 43211',
        location: 'Chandigarh, Punjab',
        status: 'active',
        totalRentals: 12,
        totalSpent: 72900,
        joinDate: 'Feb 2025',
    },
    {
        id: 'CUST-003',
        name: 'Devendra Mehta',
        initials: 'DM',
        avatarColor: 'linear-gradient(135deg, #ec4899, #be185d)',
        email: 'dev.mehta@email.com',
        phone: '+91 98765 43212',
        location: 'Ahmedabad, Gujarat',
        status: 'active',
        totalRentals: 5,
        totalSpent: 31300,
        joinDate: 'Mar 2025',
    },
    {
        id: 'CUST-004',
        name: 'Rohan Kapoor',
        initials: 'RK',
        avatarColor: 'linear-gradient(135deg, #10b981, #047857)',
        email: 'rohan.kapoor@email.com',
        phone: '+91 98765 43213',
        location: 'Delhi, NCR',
        status: 'active',
        totalRentals: 9,
        totalSpent: 81500,
        joinDate: 'Dec 2024',
    },
    {
        id: 'CUST-005',
        name: 'Karanvir Verma',
        initials: 'KV',
        avatarColor: 'linear-gradient(135deg, #f97316, #c2410c)',
        email: 'karan.verma@email.com',
        phone: '+91 98765 43214',
        location: 'Mumbai, Maharashtra',
        status: 'active',
        totalRentals: 6,
        totalSpent: 59200,
        joinDate: 'Nov 2024',
    },
    {
        id: 'CUST-006',
        name: 'Siddharth Nair',
        initials: 'SN',
        avatarColor: 'linear-gradient(135deg, #14b8a6, #0f766e)',
        email: 'siddharth.nair@email.com',
        phone: '+91 98765 43215',
        location: 'Bengaluru, Karnataka',
        status: 'inactive',
        totalRentals: 3,
        totalSpent: 38900,
        joinDate: 'Oct 2024',
    },
]

export const INITIAL_INVOICES: Invoice[] = [
    {
        id: 'INV-001',
        customerId: 'CUST-001',
        customerName: 'Vikramaditya Rathore',
        outfitId: 'OUT-001',
        outfitName: 'Royal Heritage Velvet Sherwani',
        amount: 8500,
        securityDeposit: 3000,
        depositStatus: 'held',
        date: 'Feb 10, 2026',
        returnDate: 'Feb 14, 2026',
        trialDate: 'Feb 07, 2026',
        eventDate: 'Feb 12, 2026',
        includedAccessories: ['Royal Turban (Safa)', 'Embroidered Dupatta', 'Designer Brooch'],
        alterationNotes: 'Sleeve shortened 0.5 inches; Chest fitted to 40"',
        status: 'paid',
    },
    {
        id: 'INV-002',
        customerId: 'CUST-002',
        customerName: 'Amanpreet Singh',
        outfitId: 'OUT-002',
        outfitName: 'Asymmetric Fusion Indo-Western Set',
        amount: 6200,
        securityDeposit: 2500,
        depositStatus: 'held',
        date: 'Feb 12, 2026',
        returnDate: 'Feb 15, 2026',
        trialDate: 'Feb 10, 2026',
        eventDate: 'Feb 14, 2026',
        includedAccessories: ['Pocket Square', 'Metallic Brooch'],
        alterationNotes: 'Waist taken in 1 inch',
        status: 'pending',
    },
    {
        id: 'INV-003',
        customerId: 'CUST-003',
        customerName: 'Devendra Mehta',
        outfitId: 'OUT-004',
        outfitName: 'Black-Tie Gala Dinner Tuxedo',
        amount: 5800,
        securityDeposit: 2000,
        depositStatus: 'refunded',
        date: 'Feb 05, 2026',
        returnDate: 'Feb 08, 2026',
        trialDate: 'Feb 03, 2026',
        eventDate: 'Feb 07, 2026',
        includedAccessories: ['Silk Bow Tie', 'Cummerbund'],
        alterationNotes: 'Trousers hemmed 1 inch',
        status: 'paid',
    },
    {
        id: 'INV-004',
        customerId: 'CUST-004',
        customerName: 'Rohan Kapoor',
        outfitId: 'OUT-005',
        outfitName: 'Raw Silk Kurta & Nehru Jacket Combo',
        amount: 3800,
        securityDeposit: 1500,
        depositStatus: 'held',
        date: 'Feb 14, 2026',
        returnDate: 'Feb 17, 2026',
        trialDate: 'Feb 12, 2026',
        eventDate: 'Feb 15, 2026',
        includedAccessories: ['Matching Pocket Square'],
        alterationNotes: 'Standard fit',
        status: 'pending',
    },
    {
        id: 'INV-005',
        customerId: 'CUST-005',
        customerName: 'Karanvir Verma',
        outfitId: 'OUT-003',
        outfitName: 'Heritage Jodhpuri Bandhgala Suit',
        amount: 7000,
        securityDeposit: 2500,
        depositStatus: 'refunded',
        date: 'Feb 01, 2026',
        returnDate: 'Feb 04, 2026',
        trialDate: 'Jan 29, 2026',
        eventDate: 'Feb 03, 2026',
        includedAccessories: ['Silk Pocket Square', 'Custom Cufflinks'],
        alterationNotes: 'Shoulders adjusted 0.5"',
        status: 'paid',
    },
]
